### ISSUE TITLE
RAG Pattern Recipe

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/pm#21]
Here is an incomplete list of existing example RAG examples and related resources that we can leverage in one way or another:

## IBM
* [`rag_modulo`](https://github.com/manavgup/rag_modulo/) - IBM Canada client engineering.
* [Blended RAG](https://github.com/ibm-ecosystem-engineering/Blended-RAG) - Code for paper "Retriever-Augmented Generation) Accuracy with Semantic Search and Hybrid Query-Based Retrievers"

## "Standard" RAG

* [Llama recipes for RAG](https://github.com/search?q=repo%3Ameta-llama%2Fllama-recipes+RAG&type=code)  (better link TODO...)
* [OPEA](https://opea.dev/) [RAG example](https://github.com/search?q=repo%3Aopea-project%2FGenAIExamples+RAG&type=code) 
* AutoRAG: [docs](https://docs.auto-rag.com/index.html), [Use with Ollama](https://medium.com/@autorag/optimize-rag-with-autorag-and-ollama-1a6d6b9c02af)
* [OpenSSA](https://www.openssa.org/) - More than RAG...
* [LlamaIndex](https://docs.llamaindex.ai/en/stable/optimizing/production_rag/)
* [LangChain](https://python.langchain.com/v0.2/docs/tutorials/rag/)

## GraphRAG
* [Neo4J](https://neo4j.com/developer-blog/advanced-rag-strategies-neo4j/?gad_source=1)
    * [...with LangChain (blog post)](https://medium.com/neo4j/implementing-from-local-to-global-graphrag-with-neo4j-and-langchain-constructing-the-graph-73924cc5bab4)
* [Microsoft `graphrag`](https://github.com/microsoft/graphrag)

## More Advanced...

* [Retrieval Augmented Generation or Long-Context LLMs? A Comprehensive Study and Hybrid Approach](https://arxiv.org/abs/2407.16833) (arxiv paper)

**Comment by adampingel** [comment]
Also see https://pages.github.ibm.com/solution-architectures/RAG-Cookbook-V2/generation/description/

**Comment by fayvor** [comment]
I'll do a recipe for rag using WatsonX in #121.
