### ISSUE TITLE
Make Granite Code available via Ollama

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/pm#23]

**Comment by fayvor** [comment]
Ollama does show considerable metadata about the model, along with the license and template:
https://ollama.com/gabegoodhart/granite-code:8b-128k/blobs/a8fe02e5a50c

This includes the context length as `llama.context_length`.

**Comment by gabe-l-hart** [comment]
Wow, great find! This metadata seems to all be parsed from the source `gguf` file, so we may be able to embed additional metadata during the HF -> gguf conversion
