### ISSUE TITLE
Send GitHub notifications to Discord

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/pm#93]

**Comment by adampingel** [comment]
https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

**Comment by rawkintrevo** [comment]
need list of what repos to include.

**Comment by adampingel** [comment]
If possible: "all public repos" in the `ibm-granite-community` org.  Otherwise, hard-code to the list of current public repos for that org.
